# configuration variables
MODBUS_SERVER_IP_ADDR = '192.168.1.147'
MODBUS_SERVER_PORT = 502
MODBUS_SERVER_ONE_BASED_ADDRESSING = true # modbus address starts in 1
MODBUS_SERVER_VALUE_FOR_EMERGENCY = 1
MODBUS_SERVER_VALUE_FOR_CLEAR = 2
